config/routes.rb
Gofast2::Application.routes.draw do
  
  resources :permissions

  devise_for :users

  resources :users
  
  get 'quotes' => 'quotes#new', :as => :quotes

  get 'job_applications' => 'job_applications#new', :as => :job_applications
  
  get "schedule/index"

  
  resources :quotes, :only => [:new, :create] do
  get 'thank_you', :on => :collection
  end
  
  resources :job_applications, :only => [:new, :create] do
  get 'thank_you', :on => :collection
  end
  get "index/index"

  get 'about' => 'index#about', :as => :about

  get 'contact' => 'index#contact', :as => :contact

  resources :drivers

  resources :trailers

  resources :trucks

  resources :job_postings, shallow: true do
    resources :job_applications, :only => [:new, :create] do
    get 'thank_you', :on => :collection
    end
  end
  
  resources :maintenances

  resources :trips

  resources :shipments

  resources :skids

  resources :announcements

  resources :cartages

  resources :companies

  root :to => 'index#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/announcement.rb
# This file allows access to the database through the Announcement object.
# attr_accessible defines the attributes that are allowed to be used by creating accessor and mutator methods.
# This file also validates the data before it is submitted to the database.
# The values for validation are stored in /lib/validation_values.rb
class Announcement < ActiveRecord::Base
  include Searchable
  
  attr_accessible :content, :date_posted, :posted_by, :title

  message = ValidationValues.message
  
  validates :title, :content, :posted_by, :date_posted, :presence => true
  validates :date_posted, :format => { :with => ValidationValues.date_time, :message => message }
  validates :title, :content, :format => { :with => ValidationValues.content, :message => message }
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # redirect the user if they're not signed in, except on show action
  before_filter :authenticate_user!, :except => [:show]

  include ApplicationHelper
  
  # GET /announcements
  # GET /announcements.json
  def index
    # format the date to be usable
    params[:search] = format_date params[:search]
    
    # Get announcements, order it, and configure for pagination
    @announcements = Announcement.search(params[:search], params[:column]).order(sort_column(Announcement, 'date_posted') + ' ' + sort_direction).page(params[:page]).per(10)
    
    get_params()
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    # Shows a specific announcement based on the id in the url
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    # Renders the form to create a new announcement
    # If a logged in user that is a driver accesses this, redirect them
    redirect_driver

    @announcement = Announcement.new
    # Get the user associated with the announcement (user who posted the announcement)
    @user = User.where(id: current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    # Renders the form to edit an announcement
    # If a logged in user that is a driver accesses this, redirect them
    redirect_driver
    
    @announcement = Announcement.new
    @user = User.where(id: current_user.id)
    
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    # Takes the user input and submits it to the database.
    redirect_driver
    
    params[:announcement][:posted_by] = current_user.id
    params[:announcement][:date_posted] = Time.now
    @announcement = Announcement.new(params[:announcement])
    @user = User.where(id: current_user.id)
    
    # Redirect to Show page on success, or display error
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    # Takes the user input and updates the record
    redirect_driver
    
    @announcement = Announcement.find(params[:id])
    
    # Redirect to Show page on success, or display error
    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    # Delete a record based on the id supplied in url
    redirect_driver
    
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<!-- create form used in announcements -->
<%= form_for(@announcement) do |f| %>
  <!-- if server side validation errors occur, display them here -->
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <section>
        <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
        
        <ul>
        <% @announcement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </section>
    </div>
  <% end %>

  <%= f.label :posted_by %>
  <%= f.collection_select :posted_by, @user, :id, :name, { :selected => @user.first.id }, { :size => 1, :disabled => 'disabled' } %>
  <%= f.label :title %>
  <%= f.text_field :title, :required => 'required', :pattern => ValidationValues.c_content %>
  <%= f.label :content %>
  <%= f.text_area :content, :size => '100x20', :required => 'required', :pattern => ValidationValues.c_content %>
  <%= f.label :date_posted %>
  <%= f.datetime_select :date_posted, :disabled => 'disabled' %>
  <div class="footer">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<!-- edit page with form -->
<section>
  <h2>Edit Announcement #<%= @announcement.id %></h2>
  <!-- load _form.html.erb into this page -->
  <%= render 'form' %>
  <!-- create links -->
  <p><%= link_to 'Show', @announcement, :class => 'button show' %><%= link_to 'Back', announcements_path, :class => 'button back' %></p>
</section>

app/views/announcements/index.html.erb
<!-- index page for announcements -->
<section>
  <h2>Announcements</h2>
  <p><%= link_to 'New Announcement', new_announcement_path, :class => 'button new' %><%= link_to 'Print', "reports/#{params[:controller]}" + "?column=#{@column}&direction=#{@direction}&search=#{@search}&sort=#{@sort}", :class => 'button' %></p>
  <!-- create form for search/ordering -->
  <%= form_tag announcements_path, :method => 'get', :class => 'search'  do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= label_tag :column %>
    <%= select_tag :column, options_for_select(Announcement.translated_searchable_columns(['id']), params[:column]) %>
    <%= label_tag :search %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Submit' %>
  <% end %>
  <table>
    <thead>
      <tr>
        <th scope="col"><%= sortable "posted_by", nil, @announcements, "date_posted" %></th>
        <th scope="col"><%= sortable "title", nil, @announcements, "date_posted" %></th>
        <th scope="col"><%= sortable "date_posted", nil, @announcements, "date_posted" %></th>
        <th scope="col">Content</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <!-- go through all announcement records and create rows with data -->
    <% @announcements.each do |announcement| %>
      <% user = User.find(announcement.posted_by) %>
      <tr>
        <td><%= link_to user.name, "/user/#{announcement.posted_by}" %></td>
        <td><%= announcement.title %></td>
        <td><%= format_time announcement.date_posted %></td>
	<td><%= announcement.content.truncate(40) %>
        <td><%= link_to '', announcement, :class => 'button show', :title => 'Show' %> <%= link_to '', edit_announcement_path(announcement), :class => 'button edit', :title => 'Edit' %> <%= link_to '', announcement, method: :delete, data: { confirm: 'Are you sure you want to delete announcement: ' + announcement.title + '?' }, :class => 'button destroy', :title => 'Delete' %></td>
      </tr>
    <% end %>
    <!-- display no results if announcements contains none -->
    <% if @announcements.empty? %>
      <tr>
        <td colspan="5">No results found.</td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @announcements %>
</section>

app/views/announcements/new.html.erb
<!-- new announcement form -->
<section>
  <h2>New Announcement</h2>
  <!-- load announcement from _form.html.erb -->
  <%= render 'form' %>
  <p><%= link_to 'Back', announcements_path, :class => 'button back' %></p>
</section>

app/views/announcements/show.html.erb
<!-- show specific announcement record -->
<section>
  <% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>
  <h2 class="announcement"><%= @announcement.title %></h2>
  <p><%= @announcement.date_posted.strftime('%B %e, %Y') %></p>
  <p><%= @announcement.content %></p>
  <% unless notice.nil? %>
  <% end %>
  <!-- since this page can be viewed by regular people, remove edit and back buttons -->
  <% if user_signed_in? %>
  <p>
      <%= link_to 'Edit', edit_announcement_path(@announcement), :class => 'button edit' %>
      <%= link_to 'Back', announcements_path, :class => 'button back' %>
  </p>
  <% end %>
</section>