config/routes.rb
Gofast2::Application.routes.draw do
  
  resources :permissions

  devise_for :users

  resources :users
  
  get 'quotes' => 'quotes#new', :as => :quotes

  get 'job_applications' => 'job_applications#new', :as => :job_applications
  
  get "schedule/index"

  
  resources :quotes, :only => [:new, :create] do
  get 'thank_you', :on => :collection
  end
  
  resources :job_applications, :only => [:new, :create] do
  get 'thank_you', :on => :collection
  end
  get "index/index"

  get 'about' => 'index#about', :as => :about

  get 'contact' => 'index#contact', :as => :contact

  resources :drivers

  resources :trailers

  resources :trucks

  resources :job_postings, shallow: true do
    resources :job_applications, :only => [:new, :create] do
    get 'thank_you', :on => :collection
    end
  end
  
  resources :maintenances

  resources :trips

  resources :shipments

  resources :skids

  resources :announcements

  resources :cartages

  resources :companies

  root :to => 'index#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/trailer.rb
# This file allows access to the database through the Trailer object.
# attr_accessible defines the attributes that are allowed to be used by creating accessor and mutator methods.
# This file also validates the data before it is submitted to the database.
# The values for validation are stored in /lib/validation_values.rb
class Trailer < ActiveRecord::Base
  include Searchable
  
  attr_accessible :license_plate, :make, :manufactured_year, :model, :trailer_no, :trailer_type, :vin, :location, :color
  
  message = ValidationValues.message

  validates :license_plate, :make, :manufactured_year, :model, :trailer_no, :trailer_type, :vin, :location, :color, :presence => true
  validates :manufactured_year, :trailer_no, :numericality => true
  validates :model, :color, :format => { :with => ValidationValues.alpha_numeric, :message => message }
  validates :vin, :format => { :with => ValidationValues.vin, :message => message }, :uniqueness => true
  validates :trailer_type, :inclusion => { :in => ValidationValues.trailer_type }
  validates :location, :format => { :with => ValidationValues.street, :message => message }
  validates :license_plate, :length => 3..8, :format => { :with => ValidationValues.license_plate, :message => message }, :uniqueness => true
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  # If not logged in, redirect user. Also restrict access from drivers
  before_filter :authenticate_user!, :redirect_driver
  
  include ApplicationHelper
  
  # GET /trailers
  # GET /trailers.json
  def index
    # Show all records
    params[:search] = format_date params[:search]
    
    @trailers = Trailer.search(params[:search], params[:column]).order(sort_column(Trailer, 'trailer_no') + ' ' + sort_direction).page(params[:page]).per(10)
    
    get_params()

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trailers }
    end
  end

  # GET /trailers/1
  # GET /trailers/1.json
  def show
    # Show one record
    @trailer = Trailer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trailer }
    end
  end

  # GET /trailers/new
  # GET /trailers/new.json
  def new
    # Form to create a new record
    @trailer = Trailer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trailer }
    end
  end

  # GET /trailers/1/edit
  def edit
    # Form to edit a record
    @trailer = Trailer.find(params[:id])
  end

  # POST /trailers
  # POST /trailers.json
  def create
    # Logic to create a new record
    @trailer = Trailer.new(params[:trailer])

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render json: @trailer, status: :created, location: @trailer }
      else
        format.html { render action: "new" }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trailers/1
  # PUT /trailers/1.json
  def update
    # Logic to update a record
    @trailer = Trailer.find(params[:id])

    respond_to do |format|
      if @trailer.update_attributes(params[:trailer])
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    # Logic to delete a record
    @trailer = Trailer.find(params[:id])
    @trailer.destroy

    respond_to do |format|
      format.html { redirect_to trailers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<!-- create form used in trailers -->
<%= form_for(@trailer) do |f| %>
  <!-- if server side validation errors occur, display them here -->
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <section>
        <h2><%= pluralize(@trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>
        
        <ul>
        <% @trailer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </section>
    </div>
  <% end %>

  <div class="float-left">
    <%= f.label :trailer_no %>
    <%= f.number_field :trailer_no, :required => 'required', :pattern => ValidationValues.c_integer, :placeholder => ValidationValues.p_integer %>
    <%= f.label :trailer_type %>
    <%= f.select :trailer_type, options_for_select(ValidationValues.trailer_type) %>
    <%= f.label :license_plate %>
    <%= f.text_field :license_plate, :required => 'required', :pattern => ValidationValues.c_license_plate, :placeholder => ValidationValues.p_license_plate %>
    <%= f.label :make %>
    <%= f.text_field :make, :required => 'required', :pattern => ValidationValues.c_alpha_numeric %>
    <%= f.label :model %>
    <%= f.text_field :model, :required => 'required', :pattern => ValidationValues.c_alpha_numeric %>
  </div>
  <div class="float-left">
    <%= f.label :manufactured_year %>
    <%= f.number_field :manufactured_year, :required => 'required', :pattern => ValidationValues.c_year, :placeholder => ValidationValues.p_year %>
    <%= f.label :vin %>
    <%= f.text_field :vin, :required => 'required', :pattern => ValidationValues.c_vin, :placeholder => ValidationValues.p_vin %>
    <%= f.label :location %>
    <%= f.text_field :location, :required => 'required', :pattern => ValidationValues.c_street, :placeholder => ValidationValues.p_street %>
    <%= f.label :color %>
    <%= f.text_field :color, :required => 'required', :pattern => ValidationValues.c_alpha_numeric, :placeholder => ValidationValues.p_color %>
  </div>
  <div class="clear"></div>
  <div class="footer">
    <%= f.submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<!-- edit page with form -->
<section>
  <h2>Edit Trailer #<%= @trailer.id %></h2>
  <%= render 'form' %>
  <p><%= link_to 'Show', @trailer, :class => 'button show' %> <%= link_to 'Back', trailers_path, :class => 'button back' %></p>
</section>

app/views/trailers/index.html.erb
<!-- index page for trailers -->
<section>
  <h2>Trailers</h2>
  <p><%= link_to 'New Trailer', new_trailer_path, :class => 'button new' %><%= link_to 'Print', "reports/#{params[:controller]}" + "?column=#{@column}&direction=#{@direction}&search=#{@search}&sort=#{@sort}", :class => 'button' %></p>
	  <!-- create form for search/ordering -->
  <%= form_tag trailers_path, :method => 'get', :class => 'search' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
		<%= label_tag :column %>
		<%= select_tag :column, options_for_select(Trailer.translated_searchable_columns(['id']), params[:column]) %>
		<%= label_tag :search %>
		<%= text_field_tag :search %>
		<%= submit_tag 'Submit' %>
  <% end %>
  <table>
    <thead>
      <tr>
        <th scope="col"><%= sortable "trailer_no", nil, @trailers, "trailer_no" %></th>
        <th scope="col"><%= sortable "trailer_type", nil, @trailers, "trailer_no" %></th>
        <th scope="col"><%= sortable "license_plate", nil, @trailers, "trailer_no" %></th>
        <th scope="col"><%= sortable "make", nil, @trailers, "trailer_no" %></th>
        <th scope="col"><%= sortable "model", nil, @trailers, "trailer_no" %></th>
        <th scope="col"><%= sortable "manufactured_year", 'MFD Year', @trailers, "trailer_no" %></th>
        <th scope="col"><%= sortable "vin", nil, @trailers, "trailer_no" %></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <!-- go through all trailer records and create rows with data -->
    <% @trailers.each do |trailer| %>
      <tr>
        <td><%= trailer.trailer_no %></td>
        <td><%= trailer.trailer_type %></td>
        <td><%= trailer.license_plate %></td>
        <td><%= trailer.make %></td>
        <td><%= trailer.model %></td>
        <td><%= trailer.manufactured_year %></td>
        <td><%= trailer.vin %></td>
        <td><%= link_to '', trailer, :class => 'button show', :title => 'Show' %> <%= link_to '', edit_trailer_path(trailer), :class => 'button edit', :title => 'Edit' %> <%= link_to '', trailer, method: :delete, data: { confirm: 'Are you sure you want to delete trailer no. ' + trailer.trailer_no.to_s + '?' }, :class => 'button destroy', :title => 'Delete' %></td>
      </tr>
    <% end %>
    <!-- display no results if trailers contain no records -->
    <% if @trailers.empty? %>
      <tr>
        <td colspan="8">No results found.</td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @trailers %>
</section>

app/views/trailers/new.html.erb
<!-- new trailer form -->
<section>
  <h2>New Trailer</h2>
  <%= render 'form' %>
  <p><%= link_to 'Back', trailers_path, :class => 'button back' %></p>
</section>

app/views/trailers/show.html.erb
<!-- show specific trailer record -->
<section>
  <h2>Trailer #<%= @trailer.id %></h2>
  <p id="notice"><%= notice %></p>
  <dl>
    <dt><strong>Trailer no:</strong></dt><dd><%= @trailer.trailer_no %></dd>
    <dt><strong>Trailer type:</strong></dt><dd><%= @trailer.trailer_type %></dd>
    <dt><strong>License plate:</strong></dt><dd><%= @trailer.license_plate %></dd>
    <dt><strong>Make:</strong></dt><dd><%= @trailer.make %></dd>
    <dt><strong>Model:</strong></dt><dd><%= @trailer.model %></dd>
    <dt><strong>Manufactured year:</strong></dt><dd><%= @trailer.manufactured_year %></dd>
    <dt><strong>VIN:</strong></dt><dd><%= @trailer.vin %></dd>
    <dt><strong>Estimated location:</strong></dt><dd><%= @trailer.location %></dd>
    <dt><strong>Color:</strong></dt><dd><%= @trailer.color %></dd>
  </dl>
  <p><%= link_to 'Edit', edit_trailer_path(@trailer), :class => 'button edit' %> <%= link_to 'Back', trailers_path, :class => 'button back' %></p>
</section>