config/routes.rb
Gofast2::Application.routes.draw do
  
  resources :permissions

  devise_for :users

  resources :users
  
  get 'quotes' => 'quotes#new', :as => :quotes

  get 'job_applications' => 'job_applications#new', :as => :job_applications
  
  get "schedule/index"

  
  resources :quotes, :only => [:new, :create] do
  get 'thank_you', :on => :collection
  end
  
  resources :job_applications, :only => [:new, :create] do
  get 'thank_you', :on => :collection
  end
  get "index/index"

  get 'about' => 'index#about', :as => :about

  get 'contact' => 'index#contact', :as => :contact

  resources :drivers

  resources :trailers

  resources :trucks

  resources :job_postings, shallow: true do
    resources :job_applications, :only => [:new, :create] do
    get 'thank_you', :on => :collection
    end
  end
  
  resources :maintenances

  resources :trips

  resources :shipments

  resources :skids

  resources :announcements

  resources :cartages

  resources :companies

  root :to => 'index#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/job_posting.rb
# This file allows access to the database through the JobPosting object.
# attr_accessible defines the attributes that are allowed to be used by creating accessor and mutator methods.
# This file also validates the data before it is submitted to the database.
# The values for validation are stored in /lib/validation_values.rb
class JobPosting < ActiveRecord::Base
  include Searchable
  
  attr_accessible :closing_date, :description, :post_date, :requirements, :title

  message = ValidationValues.message
  
  validates :closing_date, :description, :post_date, :requirements, :title, :presence => true
  validates :closing_date, :post_date, :format => { :with => ValidationValues.date, :message => message }
  validates :title, :requirements, :description, :format => { :with => ValidationValues.content, :message => message }
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  # Restricts access to certain pages
  before_filter :authenticate_user!, :except => [:index, :show, :apply, :process_application]
  
  include ApplicationHelper
  
  # GET /job_postings
  # GET /job_postings.json
  def index
    # Show all job applications
    params[:search] = format_date params[:search]
    
    @job_postings = JobPosting.search(params[:search], params[:column]).order(sort_column(JobPosting, 'title') + ' ' + sort_direction).page(params[:page]).per(10)
    
    get_params()

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_postings }
    end
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
    # Display one record
    @job_posting = JobPosting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_posting }
    end
  end

  # GET /job_postings/new
  # GET /job_postings/new.json
  def new
    # form to create a new record
    redirect_driver

    @job_posting = JobPosting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_posting }
    end
  end

  # GET /job_postings/1/edit
  def edit
    # Form to edit a record
    redirect_driver

    @job_posting = JobPosting.find(params[:id])
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    # Logic to create a record
    redirect_driver

    @job_posting = JobPosting.new(params[:job_posting])

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render json: @job_posting, status: :created, location: @job_posting }
      else
        format.html { render action: "new" }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_postings/1
  # PUT /job_postings/1.json
  def update
    # Logic to update a record
    redirect_driver

    @job_posting = JobPosting.find(params[:id])

    respond_to do |format|
      if @job_posting.update_attributes(params[:job_posting])
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    # Logic to delete a record
    redirect_driver

    @job_posting = JobPosting.find(params[:id])
    @job_posting.destroy

    respond_to do |format|
      format.html { redirect_to job_postings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.erb
<!-- create form used in job postings -->
<%= form_for@job_posting do |f| %>
  <!-- if server side validation errors occur, display them here -->
  <% if @job_posting.errors.any? %>
    <div id="error_explanation">
      <section>
        <h2><%= pluralize(@job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>
        
        <ul>
        <% @job_posting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </section>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title, :required => 'required', :pattern => ValidationValues.c_content %>
  <%= f.label :post_date %>
  <%= f.date_select :post_date %>
  <%= f.label :closing_date %>
  <%= f.date_select :closing_date %>
  <%= f.label :description %>
  <%= f.text_area :description, :size => '100x20', :required => 'required', :pattern => ValidationValues.c_content %>
  <%= f.label :requirements %>
  <%= f.text_field :requirements, :required => 'required', :pattern => ValidationValues.c_content, :placeholder => ValidationValues.p_requirements %>
  <div class="footer">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_postings/edit.html.erb
<!-- edit page with form -->
<section>
  <h2>Edit <%= @job_posting.title %></h2>
  <%= render 'form' %>
  <p><%= link_to 'Show', @job_posting, :class => 'button show' %> <%= link_to 'Back', job_postings_path, :class => 'button back' %></p>
</section>

app/views/job_postings/index.html.erb
<!-- index page for job postings -->
<section>
  <h2>Job Postings</h2>
  <% if user_signed_in? && current_user.access != 'driver' %>
    <p><%= link_to 'New Job posting', new_job_posting_path, :class => 'button new' %><%= link_to 'Print', "reports/#{params[:controller]}" + "?column=#{@column}&direction=#{@direction}&search=#{@search}&sort=#{@sort}", :class => 'button' %></p>
	  <!-- create form for search/ordering -->
    <%= form_tag job_postings_path, :method => 'get', :class => 'search' do %>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
		  <%= label_tag :column %>
		  <%= select_tag :column, options_for_select(JobPosting.translated_searchable_columns(['id']), params[:column]) %>
		  <%= label_tag :search %>
		  <%= text_field_tag :search %>
		  <%= submit_tag 'Submit' %>
    <% end %>
  <% end %>
  <table>
    <thead>
      <tr>
        <th scope="col"><%= sortable "title", nil, @job_postings, "title" %></th>
        <th scope="col"><%= sortable "post_date", nil, @job_postings, "title" %></th>
        <th scope="col"><%= sortable "closing_date", nil, @job_postings, "title" %></th>
        <th scope="col"><%= sortable "description", nil, @job_postings, "title" %></th>
        <th scope="col"><%= sortable "requirements", nil, @job_postings, "title" %></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <!-- go through all job posting records and create rows with data -->
    <% @job_postings.each do |job_posting| %>
      <tr>
        <td><%= job_posting.title %></td>
        <td><%= job_posting.post_date %></td>
        <td><%= job_posting.closing_date %></td>
        <td><%= job_posting.description %></td>
        <td><%= job_posting.requirements %></td>
        <td>
          <%= link_to '', job_posting, :class => 'button show', :title => 'Show' %>
          <% if user_signed_in? && current_user.access != 'driver' %>
            <%= link_to '', edit_job_posting_path(job_posting), :class => 'button edit', :title => 'Edit' %>
            <%= link_to '', job_posting, method: :delete, data: { confirm: 'Are you sure you want to delete job posting: ' + job_posting.title + '?' }, :class => 'button destroy', :title => 'Delete' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <!-- display no results if announcements contains no records -->
    <% if @job_postings.empty? %>
      <tr>
        <td colspan="6">No results found.</td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @job_postings %>
</section>

app/views/job_postings/new.html.erb
<!-- new job postings form -->
<section>
  <h2>New Job Posting</h2>
  <%= render 'form' %>
  <p><%= link_to 'Back', job_postings_path, :class => 'button back' %></p>
</section>

app/views/job_postings/show.html.erb
<!-- show specific job posting record -->
<section>
  <h2><%= @job_posting.title %></h2>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <dl class="normal">
    <dt><strong>Post date:</strong></dt><dd><%= @job_posting.post_date %></dd>
    <dt><strong>Closing date:</strong></dt><dd><%= @job_posting.closing_date %></dd>
    <dt><strong>Description:</strong></dt><dd><%= @job_posting.description %></dd>
    <dt><strong>Requirements:</strong></dt><dd><%= @job_posting.requirements %></dd>
  </dl>
  <p>
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_job_posting_path(@job_posting), :class => 'button edit' %>
    <% end %>
    <%= link_to 'Back', job_postings_path, :class => 'button back' %>
    <%= link_to 'Apply', new_job_application_path(:title => @job_posting.title), :class => 'button'%>
  </p>
</section>